# centos7-ceph-deploy/tasks/main.yml
---

  - name: create ceph cluster
    shell: >
      ceph-deploy new {{ groups.ceph_primary_node }}
    #environment:
    args:
      executable: /bin/bash

  - name: create ceph dir
    file: path=/etc/ceph state=directory mode=0755

  - name: add nodes to ceph-deploy {{ groups.ceph_nodes }}
    with_items:
    shell: >
      ceph-deploy install --release emperor {{ groups.ceph_nodes | join(' ')}}
    args:
      executable: /bin/bash

  - name: check nodes
    shell: >
      ceph -v
    register: nodes_check
    args:
      executable: /bin/bash

  - name: create monitor
    shell: >
      ceph-deploy mon create-initial
    args:
      executable: /bin/bash

  - name: create status
    shell: >
      ceph-deploy mon create-initial
    register: nodes_first_status
    args:
      executable: /bin/bash
